FUNC(objc_msgSend                  , regular)
FUNC(objc_msgSend_debug            , regular)
FUNC(objc_msgSend_noarg            , regular)
FUNC(objc_msgSend_stret            , stret)
FUNC(objc_msgSend_stret_debug      , stret)
FUNC(objc_msgSendSuper             , super)
FUNC(objc_msgSendSuper2            , super)
FUNC(objc_msgSendSuper2_debug      , super)
FUNC(objc_msgSendSuper2_stret      , super_stret)
FUNC(objc_msgSendSuper2_stret_debug, super_stret)
FUNC(objc_msgSendSuper_stret       , super_stret)

#ifndef ARM
FUNC(objc_msgSend_fixup            , fixup)
FUNC(objc_msgSend_fpret            , fpret)
FUNC(objc_msgSend_fpret_debug      , fpret)
FUNC(objc_msgSend_fp2ret           , fpret2)
FUNC(objc_msgSend_fp2ret_debug     , fpret2)
FUNC(objc_msgSend_fp2ret_fixup     , fpret2_fixup)
FUNC(objc_msgSend_fpret_fixup      , fpret_fixup)
FUNC(objc_msgSend_stret_fixup      , stret_fixup)
FUNC(objc_msgSendSuper2_fixup      , super_fixup)
FUNC(objc_msgSendSuper2_stret_fixup, super_stret_fixup)
#endif
